# Site
name: "Զնին.հայ"
title: "Զնին.հայ"
description: "առաջին հայալեզու քննախօսական կայքը"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
disqus: 'znin-hay'
google_analytics: 'UA-151918233-1'
include: ["_pages"]
permalink: /:title/
theme: mediumish-theme-jekyll

# Plugins
plugins_dir: [_plugins]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
